name: nutricoach-app
services:
- name: web
  source_dir: /
  github:
    repo: Manu5921/nutricoach
    branch: main
  build_command: npm ci && npm run build
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  envs:
  - key: NODE_ENV
    value: production
  - key: NEXT_TELEMETRY_DISABLED
    value: "1"
  - key: NEXT_PUBLIC_SUPABASE_URL
    type: SECRET
  - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
    type: SECRET
  - key: SUPABASE_SERVICE_ROLE_KEY
    type: SECRET
  - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
    type: SECRET
  - key: STRIPE_SECRET_KEY
    type: SECRET
  - key: NEXT_PUBLIC_SENTRY_DSN
    type: SECRET