# 🏭 Production Environment Configuration
# Ultra-secure production environment with maximum protection and manual approval

name: production
description: "Production environment serving live users with maximum security"

# Environment Settings
environment:
  name: production
  description: "Live production environment - requires manual approval and security review"
  
# Protection Rules - Maximum Security
protection_rules:
  # Require 2 reviewers for production deployments
  required_reviewers: 2
  
  # Extended wait time for production deployments
  wait_timer: 30 # minutes
  
  # Prevent self-review
  prevent_self_review: true
  
  # Required reviewer teams
  required_reviewer_teams:
    - "devops-team"
    - "senior-developers"
    - "security-team"
  
  # Only allow deployments from protected branches
  deployment_branch_policy:
    protected_branches: true
    custom_branches: 
      - "main"
      - "release/*"
    
  # Additional security requirements
  required_status_checks:
    - "security-scan"
    - "dependency-audit"
    - "code-quality"
    - "integration-tests"
    - "e2e-tests"
    - "performance-tests"
    - "security-review"

# Environment Variables Template
# These should be configured in GitHub UI with maximum security
environment_variables:
  # Deployment
  VERCEL_TOKEN_PRODUCTION: "{{ secrets.VERCEL_TOKEN_PRODUCTION }}"
  VERCEL_ORG_ID: "{{ secrets.VERCEL_ORG_ID }}"
  VERCEL_PROJECT_ID_PRODUCTION: "{{ secrets.VERCEL_PROJECT_ID_PRODUCTION }}"
  
  # Database - Production
  SUPABASE_ACCESS_TOKEN: "{{ secrets.SUPABASE_ACCESS_TOKEN }}"
  SUPABASE_PROJECT_REF_PRODUCTION: "{{ secrets.SUPABASE_PROJECT_REF_PRODUCTION }}"
  SUPABASE_DB_URL_PRODUCTION: "{{ secrets.SUPABASE_DB_URL_PRODUCTION }}"
  SUPABASE_ANON_KEY_PRODUCTION: "{{ secrets.SUPABASE_ANON_KEY_PRODUCTION }}"
  SUPABASE_SERVICE_ROLE_KEY_PRODUCTION: "{{ secrets.SUPABASE_SERVICE_ROLE_KEY_PRODUCTION }}"
  
  # Application - Production
  NEXTAUTH_SECRET_PRODUCTION: "{{ secrets.NEXTAUTH_SECRET_PRODUCTION }}"
  NEXTAUTH_URL_PRODUCTION: "{{ secrets.NEXTAUTH_URL_PRODUCTION }}"
  JWT_SECRET_PRODUCTION: "{{ secrets.JWT_SECRET_PRODUCTION }}"
  ENCRYPTION_KEY_PRODUCTION: "{{ secrets.ENCRYPTION_KEY_PRODUCTION }}"
  
  # External Services - Production
  OPENAI_API_KEY_PRODUCTION: "{{ secrets.OPENAI_API_KEY_PRODUCTION }}"
  STRIPE_SECRET_KEY_PRODUCTION: "{{ secrets.STRIPE_SECRET_KEY_PRODUCTION }}"
  STRIPE_WEBHOOK_SECRET_PRODUCTION: "{{ secrets.STRIPE_WEBHOOK_SECRET_PRODUCTION }}"
  SENDGRID_API_KEY_PRODUCTION: "{{ secrets.SENDGRID_API_KEY_PRODUCTION }}"
  
  # Monitoring - Production
  SENTRY_DSN_PRODUCTION: "{{ secrets.SENTRY_DSN_PRODUCTION }}"
  DATADOG_API_KEY_PRODUCTION: "{{ secrets.DATADOG_API_KEY_PRODUCTION }}"
  NEW_RELIC_LICENSE_KEY: "{{ secrets.NEW_RELIC_LICENSE_KEY }}"
  
  # Security
  SECURITY_MONITORING_TOKEN: "{{ secrets.SECURITY_MONITORING_TOKEN }}"
  AUDIT_LOG_TOKEN: "{{ secrets.AUDIT_LOG_TOKEN }}"

# Security Validation Rules - Maximum Security
security_rules:
  # Comprehensive security checks required
  required_checks:
    - "security-scan"
    - "vulnerability-scan"
    - "penetration-test"
    - "dependency-audit"
    - "secret-validation"
    - "code-quality"
    - "compliance-check"
    - "performance-test"
    - "load-test"
    - "security-review"
    - "change-management-approval"
    
  # Manual deployment only
  auto_deploy:
    enabled: false
    require_manual_approval: true
    require_security_review: true
    
  # Enhanced monitoring
  monitoring:
    enabled: true
    real_time: true
    alerts:
      - "deployment-failure"
      - "security-violations"
      - "performance-degradation"
      - "error-rate-spike"
      - "availability-issues"
      
  # Security incident response
  incident_response:
    enabled: true
    immediate_escalation: true
    contacts:
      - "security@nutricoach.com"
      - "cto@nutricoach.com"
      - "incident-commander@nutricoach.com"

# Deployment Configuration - Maximum Safety
deployment:
  # Blue-green deployment strategy
  strategy: "blue-green"
  
  # Comprehensive health checks
  health_checks:
    enabled: true
    paths:
      - "/api/health"
      - "/api/health/db"
      - "/api/health/external"
    timeout: 60 # seconds
    retries: 3
    
  # Advanced rollback configuration
  rollback:
    enabled: true
    automatic: true
    conditions:
      - "health_check_failure"
      - "error_rate_threshold"
      - "performance_degradation"
      - "security_violation"
    manual_override: true
    
  # Canary deployment support
  canary:
    enabled: true
    percentage: 10 # Start with 10% traffic
    duration: 300 # 5 minutes
    success_criteria:
      - "error_rate < 0.1%"
      - "response_time < 500ms"
      - "availability > 99.9%"

# Change Management
change_management:
  # Require change management approval
  required: true
  
  # Change advisory board
  approvers:
    - "change-manager@nutricoach.com"
    - "security-lead@nutricoach.com"
    - "devops-lead@nutricoach.com"
    
  # Documentation requirements
  documentation:
    required: true
    items:
      - "change_description"
      - "impact_assessment"
      - "rollback_plan"
      - "testing_evidence"
      - "security_review"
      - "risk_assessment"
      
  # Deployment windows
  deployment_windows:
    - day: "tuesday"
      start: "10:00"
      end: "14:00"
      timezone: "UTC"
    - day: "thursday"
      start: "10:00"
      end: "14:00"
      timezone: "UTC"

# Notification Settings - Multiple Channels
notifications:
  # Critical alerts
  critical:
    - type: "slack"
      webhook_url: "{{ secrets.SLACK_WEBHOOK_URL }}"
      channels:
        - "#production-alerts"
        - "#security-incidents"
        - "#leadership"
    
    - type: "email"
      recipients:
        - "cto@nutricoach.com"
        - "security@nutricoach.com"
        - "devops@nutricoach.com"
        - "incident-commander@nutricoach.com"
        
    - type: "pagerduty"
      service_key: "{{ secrets.PAGER_DUTY_SERVICE_KEY }}"
      escalation_policy: "production-incidents"
      
  # Standard alerts
  standard:
    - type: "slack"
      webhook_url: "{{ secrets.SLACK_WEBHOOK_URL }}"
      channels:
        - "#production-deployments"
        - "#devops"
        
    - type: "email"
      recipients:
        - "devops@nutricoach.com"
        - "security@nutricoach.com"

# Audit and Compliance - Maximum Tracking
audit_settings:
  # Comprehensive logging
  logging:
    enabled: true
    retention_days: 2555 # 7 years for compliance
    encryption: true
    
  # Compliance frameworks
  compliance:
    gdpr: true
    ccpa: true
    soc2: true
    iso27001: true
    pci_dss: false # Update if handling payments directly
    
  # Audit trails
  audit_trails:
    - "deployment_activities"
    - "access_logs"
    - "configuration_changes"
    - "security_events"
    - "data_access"
    - "user_activities"
    
  # Regular audits
  scheduled_audits:
    - frequency: "daily"
      type: "security_scan"
    - frequency: "weekly"
      type: "access_review"
    - frequency: "monthly"
      type: "compliance_check"
    - frequency: "quarterly"
      type: "full_security_audit"

# Business Continuity
business_continuity:
  # High availability configuration
  high_availability:
    enabled: true
    multi_region: true
    auto_failover: true
    
  # Disaster recovery
  disaster_recovery:
    enabled: true
    rpo: 15 # minutes (Recovery Point Objective)
    rto: 60 # minutes (Recovery Time Objective)
    backup_frequency: "hourly"
    
  # Maintenance windows
  maintenance_windows:
    - day: "sunday"
      start: "02:00"
      end: "06:00"
      timezone: "UTC"
      type: "emergency_only"

# Documentation and Contacts
documentation:
  runbook_url: "https://docs.nutricoach.com/deployments/production"
  incident_response: "https://docs.nutricoach.com/security/incident-response"
  change_management: "https://docs.nutricoach.com/processes/change-management"
  security_procedures: "https://docs.nutricoach.com/security/procedures"
  
  # Emergency contacts
  contact_info:
    incident_commander: "incident-commander@nutricoach.com"
    security_lead: "security-lead@nutricoach.com"
    devops_lead: "devops-lead@nutricoach.com"
    cto: "cto@nutricoach.com"
    legal: "legal@nutricoach.com"
    
    # 24/7 contacts
    security_hotline: "+1-555-SECURITY"
    devops_oncall: "+1-555-DEVOPS"
    incident_hotline: "+1-555-INCIDENT"

# Metadata
metadata:
  created_by: "Security Team"
  last_updated: "2024-12-24"
  version: "1.0"
  review_date: "2025-01-24"
  classification: "CONFIDENTIAL"
  compliance_validated: true
  security_approved: true