# 🏭🗃️ Production Database Environment Configuration
# Ultra-secure production database with maximum protection and DBA approval required

name: production-db
description: "Ultra-secure production database environment with mandatory approvals"

# Environment Settings
environment:
  name: production-db
  description: "Production database environment - requires DBA, Security, and DevOps approval"
  
# Protection Rules - Ultra-Maximum Security
protection_rules:
  # Require 3 reviewers for production database operations
  required_reviewers: 3
  
  # Extended wait time for production database operations
  wait_timer: 60 # minutes
  
  # Prevent self-review
  prevent_self_review: true
  
  # Required reviewer teams - Ultra-secure approval process
  required_reviewer_teams:
    - "database-admin-team"    # DBA approval mandatory
    - "security-team"          # Security review mandatory
    - "senior-devops-team"     # DevOps approval mandatory
  
  # Only allow deployments from protected branches
  deployment_branch_policy:
    protected_branches: true
    custom_branches: 
      - "main"
      - "release/*"
      - "hotfix/db-*"
    
  # Comprehensive security requirements
  required_status_checks:
    - "migration-safety"
    - "schema-validation"
    - "data-integrity"
    - "security-scan"
    - "compliance-check"
    - "backup-verification"
    - "rollback-test"
    - "performance-impact"
    - "dba-review"
    - "security-review"
    - "change-management-approval"

# Environment Variables Template
# Production database secrets with maximum security
environment_variables:
  # Supabase Database - Production
  SUPABASE_ACCESS_TOKEN: "{{ secrets.SUPABASE_ACCESS_TOKEN }}"
  SUPABASE_PROJECT_REF_PRODUCTION: "{{ secrets.SUPABASE_PROJECT_REF_PRODUCTION }}"
  SUPABASE_DB_URL_PRODUCTION: "{{ secrets.SUPABASE_DB_URL_PRODUCTION }}"
  SUPABASE_SERVICE_ROLE_KEY_PRODUCTION: "{{ secrets.SUPABASE_SERVICE_ROLE_KEY_PRODUCTION }}"
  SUPABASE_JWT_SECRET_PRODUCTION: "{{ secrets.SUPABASE_JWT_SECRET_PRODUCTION }}"
  SUPABASE_ANON_KEY_PRODUCTION: "{{ secrets.SUPABASE_ANON_KEY_PRODUCTION }}"
  
  # Database Administration
  DATABASE_ADMIN_TOKEN: "{{ secrets.DATABASE_ADMIN_TOKEN }}"
  DATABASE_MIGRATION_TOKEN_PRODUCTION: "{{ secrets.DATABASE_MIGRATION_TOKEN_PRODUCTION }}"
  DATABASE_REPLICATION_TOKEN: "{{ secrets.DATABASE_REPLICATION_TOKEN }}"
  
  # Backup and Recovery - Production
  DATABASE_BACKUP_TOKEN_PRODUCTION: "{{ secrets.DATABASE_BACKUP_TOKEN_PRODUCTION }}"
  DATABASE_RESTORE_TOKEN_PRODUCTION: "{{ secrets.DATABASE_RESTORE_TOKEN_PRODUCTION }}"
  DATABASE_ENCRYPTION_KEY: "{{ secrets.DATABASE_ENCRYPTION_KEY }}"
  
  # Monitoring and Alerting - Production
  DATABASE_MONITORING_TOKEN_PRODUCTION: "{{ secrets.DATABASE_MONITORING_TOKEN_PRODUCTION }}"
  DATADOG_DATABASE_API_KEY: "{{ secrets.DATADOG_DATABASE_API_KEY }}"
  NEW_RELIC_DATABASE_KEY: "{{ secrets.NEW_RELIC_DATABASE_KEY }}"
  SENTRY_DSN_PRODUCTION: "{{ secrets.SENTRY_DSN_PRODUCTION }}"
  
  # Security and Compliance
  DATABASE_AUDIT_TOKEN: "{{ secrets.DATABASE_AUDIT_TOKEN }}"
  COMPLIANCE_MONITORING_TOKEN: "{{ secrets.COMPLIANCE_MONITORING_TOKEN }}"
  SECURITY_SCANNER_TOKEN: "{{ secrets.SECURITY_SCANNER_TOKEN }}"

# Database Security Rules - Ultra-Maximum Security
security_rules:
  # Comprehensive security checks required
  required_checks:
    - "migration-safety"
    - "schema-validation"
    - "data-integrity"
    - "sql-injection-scan"
    - "privilege-escalation-check"
    - "backup-verification"
    - "rollback-test"
    - "performance-impact-analysis"
    - "security-vulnerability-scan"
    - "compliance-validation"
    - "data-classification-check"
    - "encryption-verification"
    - "access-control-validation"
    - "audit-trail-verification"
    
  # Manual approval only - no auto-deployment
  auto_deploy:
    enabled: false
    require_manual_approval: true
    require_dba_approval: true
    require_security_review: true
    require_change_management: true
    
  # Real-time monitoring with immediate alerts
  monitoring:
    enabled: true
    real_time: true
    metrics:
      - "query-performance"
      - "connection-pool"
      - "lock-detection"
      - "deadlock-monitoring"
      - "storage-usage"
      - "replication-lag"
      - "backup-status"
      - "security-events"
      - "compliance-violations"
    alerts:
      - "migration-failure"
      - "data-corruption"
      - "performance-degradation"
      - "security-violations"
      - "unauthorized-access"
      - "backup-failure"
      - "replication-issues"
      - "compliance-breach"

# Change Management - Mandatory Process
change_management:
  # Require comprehensive change management
  required: true
  
  # Change Advisory Board for Database
  approvers:
    - "database-change-manager@nutricoach.com"
    - "senior-dba@nutricoach.com"
    - "security-database-lead@nutricoach.com"
    - "compliance-officer@nutricoach.com"
    
  # Comprehensive documentation requirements
  documentation:
    required: true
    items:
      - "migration_description"
      - "impact_assessment"
      - "rollback_plan"
      - "testing_evidence"
      - "security_review"
      - "risk_assessment"
      - "performance_impact"
      - "data_classification_impact"
      - "compliance_validation"
      - "disaster_recovery_impact"
      
  # Strict deployment windows
  deployment_windows:
    - day: "tuesday"
      start: "09:00"
      end: "11:00"
      timezone: "UTC"
      type: "planned_maintenance"
    - day: "thursday"
      start: "09:00"
      end: "11:00"
      timezone: "UTC"
      type: "planned_maintenance"
    - day: "any"
      start: "00:00"
      end: "23:59"
      timezone: "UTC"
      type: "emergency_only"

# Migration Configuration - Ultra-Safe
migration:
  # Sequential migration strategy with extensive validation
  strategy: "sequential-with-validation"
  
  # Comprehensive pre-migration checks
  pre_migration_checks:
    - name: "dba_approval_verification"
      command: "npm run db:verify-dba-approval"
      timeout: 60
      required: true
      
    - name: "security_clearance_check"
      command: "npm run db:verify-security-clearance"
      timeout: 60
      required: true
      
    - name: "schema_validation"
      command: "npm run db:validate-schema-production"
      timeout: 120
      required: true
      
    - name: "full_backup_verification"
      command: "npm run db:full-backup-production"
      timeout: 1800 # 30 minutes
      required: true
      
    - name: "migration_dry_run"
      command: "npm run db:migrate-dry-run-production"
      timeout: 300
      required: true
      
    - name: "rollback_verification"
      command: "npm run db:verify-rollback-production"
      timeout: 180
      required: true
      
    - name: "performance_impact_analysis"
      command: "npm run db:analyze-performance-impact"
      timeout: 300
      required: true
      
    - name: "compliance_validation"
      command: "npm run db:validate-compliance"
      timeout: 180
      required: true
      
  # Migration execution with maximum safety
  migration_execution:
    timeout: 1800 # 30 minutes
    retry_attempts: 1 # No retries in production
    rollback_on_failure: true
    immediate_notification: true
    
  # Comprehensive post-migration validation
  post_migration_checks:
    - name: "data_integrity"
      command: "npm run db:verify-integrity-production"
      timeout: 600
      required: true
      
    - name: "performance_validation"
      command: "npm run db:performance-test-production"
      timeout: 300
      required: true
      
    - name: "security_scan"
      command: "npm run db:security-scan-production"
      timeout: 600
      required: true
      
    - name: "compliance_verification"
      command: "npm run db:verify-compliance-production"
      timeout: 300
      required: true
      
    - name: "backup_integrity_check"
      command: "npm run db:verify-backup-integrity"
      timeout: 300
      required: true

# Deployment Configuration - Maximum Safety
deployment:
  # Blue-green deployment for database
  strategy: "blue-green-database"
  
  # Comprehensive health checks
  health_checks:
    enabled: true
    checks:
      - name: "database_connection"
        endpoint: "/api/health/db"
        timeout: 60
        retries: 5
        
      - name: "migration_status"
        endpoint: "/api/health/migrations"
        timeout: 30
        retries: 3
        
      - name: "data_consistency"
        endpoint: "/api/health/data-integrity"
        timeout: 120
        retries: 3
        
      - name: "replication_status"
        endpoint: "/api/health/replication"
        timeout: 60
        retries: 3
        
      - name: "backup_status"
        endpoint: "/api/health/backup"
        timeout: 90
        retries: 2
    
  # Advanced rollback configuration
  rollback:
    enabled: true
    automatic: true
    conditions:
      - "migration_failure"
      - "data_corruption"
      - "performance_degradation"
      - "integrity_violation"
      - "security_violation"
      - "compliance_violation"
    backup_required: true
    dba_notification: true
    immediate_escalation: true

# Data Protection - Maximum Security
data_protection:
  # Advanced backup configuration
  backup:
    enabled: true
    frequency: "before_each_operation"
    retention: 2555 # 7 years for compliance
    encryption: true
    compression: true
    cross_region_replication: true
    immutable_backups: true
    
  # Comprehensive data masking
  data_masking:
    enabled: true
    fields:
      - "users.email"
      - "users.phone"
      - "users.address"
      - "payment.card_number"
      - "payment.bank_details"
      - "profile.personal_data"
      - "health.medical_info"
      - "auth.password_hash"
      
  # Strict data retention policies
  retention_policies:
    - table: "audit_logs"
      retention_days: 2555 # 7 years
    - table: "security_events"
      retention_days: 2555 # 7 years
    - table: "user_activities"
      retention_days: 1095 # 3 years
    - table: "session_data"
      retention_days: 90
    - table: "temp_data"
      retention_days: 1
      
  # Data classification enforcement
  data_classification:
    - classification: "public"
      tables: ["categories", "tags", "public_content"]
      encryption: false
      backup_frequency: "daily"
      
    - classification: "internal"
      tables: ["recipes", "blog_posts", "app_config"]
      encryption: true
      backup_frequency: "hourly"
      
    - classification: "confidential"
      tables: ["users", "user_profiles", "user_preferences"]
      encryption: true
      backup_frequency: "every_15_minutes"
      access_logging: true
      
    - classification: "restricted"
      tables: ["payments", "personal_health_data", "auth_tokens"]
      encryption: true
      backup_frequency: "continuous"
      access_logging: true
      approval_required: true

# Monitoring and Alerting - Comprehensive
monitoring:
  # Real-time database metrics
  metrics:
    - "connection_count"
    - "active_connections"
    - "query_performance"
    - "slow_queries"
    - "storage_usage"
    - "iops_utilization"
    - "migration_status"
    - "replication_lag"
    - "backup_status"
    - "security_events"
    - "failed_authentication_attempts"
    - "privilege_escalations"
    - "data_access_patterns"
    - "compliance_violations"
    
  # Strict performance thresholds
  thresholds:
    query_time_warning: 500 # ms
    query_time_critical: 1000 # ms
    connection_warning: 70 # percent
    connection_critical: 85 # percent
    storage_warning: 70 # percent
    storage_critical: 85 # percent
    replication_lag_warning: 30 # seconds
    replication_lag_critical: 60 # seconds
    backup_age_warning: 86400 # seconds (24 hours)
    backup_age_critical: 172800 # seconds (48 hours)
    
  # Multi-channel alerting
  alerts:
    # Critical alerts - Immediate response
    critical:
      - type: "pagerduty"
        service_key: "{{ secrets.PAGER_DUTY_DATABASE_KEY }}"
        escalation_policy: "database-critical"
        
      - type: "slack"
        webhook_url: "{{ secrets.SLACK_WEBHOOK_URL }}"
        channels:
          - "#database-critical"
          - "#security-incidents"
          - "#leadership"
          
      - type: "email"
        recipients:
          - "dba-oncall@nutricoach.com"
          - "security-oncall@nutricoach.com"
          - "cto@nutricoach.com"
          - "incident-commander@nutricoach.com"
          
      - type: "sms"
        recipients:
          - "+1-555-DBA-ONCALL"
          - "+1-555-SECURITY-ONCALL"
    
    # Warning alerts - 1 hour response
    warning:
      - type: "slack"
        webhook_url: "{{ secrets.SLACK_WEBHOOK_URL }}"
        channels:
          - "#database-alerts"
          - "#devops"
          
      - type: "email"
        recipients:
          - "database@nutricoach.com"
          - "devops@nutricoach.com"
          - "security@nutricoach.com"

# Compliance and Audit - Maximum Coverage
compliance:
  # Data governance frameworks
  data_governance:
    enabled: true
    frameworks:
      - "GDPR"
      - "CCPA"
      - "SOC2"
      - "ISO27001"
      - "HIPAA" # If health data is involved
      
  # Comprehensive audit logging
  audit_logging:
    enabled: true
    retention_years: 7
    encryption: true
    immutable: true
    events:
      - "schema_changes"
      - "data_modifications"
      - "access_attempts"
      - "failed_access_attempts"
      - "privilege_changes"
      - "migration_events"
      - "backup_operations"
      - "restore_operations"
      - "configuration_changes"
      - "security_events"
      - "compliance_checks"
      
  # Regular compliance checks
  scheduled_compliance:
    - frequency: "hourly"
      type: "access_pattern_analysis"
    - frequency: "daily"
      type: "data_integrity_check"
    - frequency: "weekly"
      type: "privilege_review"
    - frequency: "monthly"
      type: "compliance_assessment"
    - frequency: "quarterly"
      type: "full_security_audit"

# Disaster Recovery - Enterprise Grade
disaster_recovery:
  # Multi-tier backup strategy
  backup_strategy:
    continuous_backup:
      enabled: true
      point_in_time_recovery: true
      
    full_backup:
      frequency: "every_6_hours"
      retention: 2555 # days
      cross_region: true
      
    incremental_backup:
      frequency: "every_15_minutes"
      retention: 90 # days
      
    transaction_log_backup:
      frequency: "continuous"
      retention: 30 # days
      
  # Recovery procedures
  recovery_procedures:
    point_in_time_recovery: true
    cross_region_replication: true
    automated_failover: true
    manual_failover_testing: "monthly"
    
  # Recovery objectives - Enterprise SLA
  rto: 15 # minutes (Recovery Time Objective)
  rpo: 1 # minute (Recovery Point Objective)
  
  # Business continuity
  business_continuity:
    multi_region_deployment: true
    active_active_replication: true
    automatic_disaster_detection: true
    disaster_communication_plan: true

# Security Controls - Maximum Security
security_controls:
  # Access controls
  access_control:
    multi_factor_authentication: true
    role_based_access: true
    principle_of_least_privilege: true
    time_limited_access: true
    session_recording: true
    
  # Network security
  network_security:
    vpc_isolation: true
    private_subnets: true
    security_groups: "restrictive"
    network_acls: "deny_by_default"
    ssl_tls_encryption: "enforced"
    
  # Data security
  data_security:
    encryption_at_rest: true
    encryption_in_transit: true
    field_level_encryption: true
    key_rotation: "automatic"
    secure_key_management: true
    
  # Monitoring and detection
  security_monitoring:
    intrusion_detection: true
    anomaly_detection: true
    behavior_analysis: true
    threat_intelligence: true
    security_information_event_management: true

# Documentation and Contacts
documentation:
  runbook_url: "https://docs.nutricoach.com/database/production-operations"
  disaster_recovery_plan: "https://docs.nutricoach.com/database/disaster-recovery"
  security_procedures: "https://docs.nutricoach.com/database/security"
  compliance_guide: "https://docs.nutricoach.com/database/compliance"
  incident_response: "https://docs.nutricoach.com/security/database-incidents"
  
  # Emergency contacts
  contact_info:
    dba_lead: "dba-lead@nutricoach.com"
    security_lead: "security-database@nutricoach.com"
    compliance_officer: "compliance@nutricoach.com"
    incident_commander: "incident-commander@nutricoach.com"
    legal_counsel: "legal@nutricoach.com"
    
    # 24/7 emergency contacts
    dba_oncall: "+1-555-DBA-ONCALL"
    security_oncall: "+1-555-SEC-ONCALL"
    incident_hotline: "+1-555-DB-INCIDENT"
    executive_escalation: "+1-555-EXEC-ESCALATION"

# Metadata
metadata:
  created_by: "Database Security Team"
  last_updated: "2024-12-24"
  version: "1.0"
  review_date: "2025-01-24"
  classification: "TOP SECRET"
  compliance_validated: true
  security_approved: true
  dba_approved: true
  legal_reviewed: true
  database_version: "PostgreSQL 15"
  supabase_tier: "Enterprise"
  sla_tier: "Mission Critical"